import { DynamoDBClient, PutItemCommand } from "@aws-sdk/client-dynamodb";

const client = new DynamoDBClient({ region: "eu-north-1" });

const quotes = [
  { id: "006", text: "Imagination is more important than knowledge.", author: "Albert Einstein", category: "creativity", year: 1929 },
  { id: "007", text: "Life is what happens when you are busy making other plans.", author: "Allen Saunders", category: "life", year: 1957 },
  { id: "008", text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu", category: "perseverance", year: 500 },
  { id: "009", text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche", category: "resilience", year: 1888 },
  { id: "010", text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "action", year: 1913 },
  { id: "011", text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "wisdom", year: 400 },
  { id: "012", text: "In the end, it is not the years in your life that count, it is the life in your years.", author: "Abraham Lincoln", category: "life", year: 1860 },
  { id: "013", text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "perseverance", year: 500 },
  { id: "014", text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius", category: "resilience", year: 500 },
  { id: "015", text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "wisdom", year: 350 },
  { id: "016", text: "The unexamined life is not worth living.", author: "Socrates", category: "philosophy", year: 399 },
  { id: "017", text: "Happiness depends upon ourselves.", author: "Aristotle", category: "happiness", year: 350 },
  { id: "018", text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", category: "purpose", year: 1888 },
  { id: "019", text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "action", year: 1900 },
  { id: "020", text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "change", year: 1913 },
  { id: "021", text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", category: "learning", year: 1913 },
  { id: "022", text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi", category: "perseverance", year: 1918 },
  { id: "023", text: "The mind is everything. What you think you become.", author: "Buddha", category: "mindset", year: 500 },
  { id: "024", text: "Peace comes from within. Do not seek it without.", author: "Buddha", category: "peace", year: 500 },
  { id: "025", text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha", category: "truth", year: 500 },
  { id: "026", text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr.", category: "hope", year: 1963 },
  { id: "027", text: "The time is always right to do what is right.", author: "Martin Luther King Jr.", category: "action", year: 1964 },
  { id: "028", text: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr.", category: "hope", year: 1963 },
  { id: "029", text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", category: "confidence", year: 1937 },
  { id: "030", text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "dreams", year: 1940 },
  { id: "031", text: "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.", author: "Eleanor Roosevelt", category: "courage", year: 1960 },
  { id: "032", text: "I have not failed. I have just found 10,000 ways that won't work.", author: "Thomas Edison", category: "perseverance", year: 1910 },
  { id: "033", text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison", category: "work", year: 1903 },
  { id: "034", text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "action", year: 1950 },
  { id: "035", text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney", category: "dreams", year: 1955 },
  { id: "036", text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "hope", year: 350 },
  { id: "037", text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", category: "love", year: 1970 },
  { id: "038", text: "If you judge people, you have no time to love them.", author: "Mother Teresa", category: "love", year: 1975 },
  { id: "039", text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", category: "life", year: 1954 },
  { id: "040", text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo", category: "hope", year: 1862 },
  { id: "041", text: "To love another person is to see the face of God.", author: "Victor Hugo", category: "love", year: 1862 },
  { id: "042", text: "It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.", author: "Jane Austen", category: "humor", year: 1813 },
  { id: "043", text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott", category: "courage", year: 1868 },
  { id: "044", text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt", category: "courage", year: 1950 },
  { id: "045", text: "Well-behaved women seldom make history.", author: "Laurel Thatcher Ulrich", category: "women", year: 1976 },
  { id: "046", text: "A woman is like a tea bag — you never know how strong she is until she gets in hot water.", author: "Eleanor Roosevelt", category: "women", year: 1940 },
  { id: "047", text: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa", category: "change", year: 1979 },
  { id: "048", text: "Try to be a rainbow in someone else's cloud.", author: "Maya Angelou", category: "kindness", year: 1993 },
  { id: "049", text: "Nothing will work unless you do.", author: "Maya Angelou", category: "work", year: 1993 },
  { id: "050", text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou", category: "resilience", year: 1993 },
  { id: "051", text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker", category: "empowerment", year: 1983 },
  { id: "052", text: "Wherever you go, go with all your heart.", author: "Confucius", category: "purpose", year: 500 },
  { id: "053", text: "He who learns but does not think is lost. He who thinks but does not learn is in great danger.", author: "Confucius", category: "learning", year: 500 },
  { id: "054", text: "Real generosity toward the future lies in giving all to the present.", author: "Albert Camus", category: "life", year: 1942 },
  { id: "055", text: "You will never be happy if you continue to search for what happiness consists of.", author: "Albert Camus", category: "happiness", year: 1942 },
  { id: "056", text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus", category: "resilience", year: 1952 },
  { id: "057", text: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson", category: "greatness", year: 1841 },
  { id: "058", text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "mindset", year: 1841 },
  { id: "059", text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "courage", year: 1841 },
  { id: "060", text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain", category: "purpose", year: 1900 },
  { id: "061", text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "courage", year: 1894 },
  { id: "062", text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain", category: "learning", year: 1900 },
  { id: "063", text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Mark Twain", category: "action", year: 1900 },
  { id: "064", text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", category: "creativity", year: 1490 },
  { id: "065", text: "Learning never exhausts the mind.", author: "Leonardo da Vinci", category: "learning", year: 1500 },
  { id: "066", text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Leonardo da Vinci", category: "action", year: 1500 },
  { id: "067", text: "Nature never hurries, yet everything is accomplished.", author: "Lao Tzu", category: "patience", year: 500 },
  { id: "068", text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", category: "change", year: 500 },
  { id: "069", text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", category: "simplicity", year: 500 },
  { id: "070", text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", category: "perseverance", year: 500 },
  { id: "071", text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", category: "learning", year: 1750 },
  { id: "072", text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin", category: "learning", year: 1750 },
  { id: "073", text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", category: "perseverance", year: 1750 },
  { id: "074", text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin", category: "purpose", year: 1750 },
  { id: "075", text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman", category: "positivity", year: 1860 },
  { id: "076", text: "Do I contradict myself? Very well then I contradict myself. I am large. I contain multitudes.", author: "Walt Whitman", category: "identity", year: 1855 },
  { id: "077", text: "Not I, nor anyone else can travel that road for you.", author: "Walt Whitman", category: "independence", year: 1855 },
  { id: "078", text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates", category: "change", year: 400 },
  { id: "079", text: "Wonder is the beginning of wisdom.", author: "Socrates", category: "wisdom", year: 400 },
  { id: "080", text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates", category: "learning", year: 400 },
  { id: "081", text: "Pleasure in the job puts perfection in the work.", author: "Aristotle", category: "work", year: 350 },
  { id: "082", text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "excellence", year: 350 },
  { id: "083", text: "The whole is more than the sum of its parts.", author: "Aristotle", category: "philosophy", year: 350 },
  { id: "084", text: "Quality is not an act, it is a habit.", author: "Aristotle", category: "excellence", year: 350 },
  { id: "085", text: "It is not enough to have a good mind. The main thing is to use it well.", author: "René Descartes", category: "wisdom", year: 1637 },
  { id: "086", text: "I think, therefore I am.", author: "René Descartes", category: "philosophy", year: 1637 },
  { id: "087", text: "The greatest remedy for anger is delay.", author: "Seneca", category: "patience", year: 60 },
  { id: "088", text: "It is not that I am so smart, it is just that I stay with problems longer.", author: "Albert Einstein", category: "perseverance", year: 1929 },
  { id: "089", text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "courage", year: 1929 },
  { id: "090", text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein", category: "creativity", year: 1929 },
  { id: "091", text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein", category: "happiness", year: 1929 },
  { id: "092", text: "The important thing is not to stop questioning.", author: "Albert Einstein", category: "curiosity", year: 1929 },
  { id: "093", text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "purpose", year: 1929 },
  { id: "094", text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", category: "values", year: 1929 },
  { id: "095", text: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "adaptability", year: 1929 },
  { id: "096", text: "You cannot shake hands with a clenched fist.", author: "Indira Gandhi", category: "peace", year: 1971 },
  { id: "097", text: "There are two kinds of people, those who do the work and those who take the credit.", author: "Indira Gandhi", category: "work", year: 1970 },
  { id: "098", text: "My grandfather once told me that there were two kinds of people: those who do the work and those who take the credit.", author: "Indira Gandhi", category: "wisdom", year: 1970 },
  { id: "099", text: "The power to question is the basis of all human progress.", author: "Indira Gandhi", category: "curiosity", year: 1970 },
  { id: "100", text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", category: "strength", year: 1913 },
];

async function addQuotes() {
  console.log(`Adding ${quotes.length} quotes...`);
  for (const q of quotes) {
    await client.send(new PutItemCommand({
      TableName: "quotes",
      Item: {
        id: { S: q.id },
        text: { S: q.text },
        author: { S: q.author },
        category: { S: q.category },
        year: { N: String(q.year) },
      }
    }));
    console.log(`✓ Added quote ${q.id}`);
  }
  console.log("All done!");
}

addQuotes();